name: AskTheCrowdsServer
version: 0.0.1
author: Max Horstmann
description: Server back-end for "Ask the Crowds" app
dependencies:
  http_server: any
  path: any
  redis_client: '>=0.1.9'
  unittest: any
  uuid: any
