# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "Ask the Crowds Server" do
  end
  config.vm.box = "Ask the Crowds Server"
  #
  # THE URL FROM WHERE THE 'CONFIG.VM.BOX' BOX WILL BE FETCHED IF IT
  # DOESN'T ALREADY EXIST ON THE USER'S SYSTEM.
  config.vm.box_url = "http://goo.gl/8kWkm"

  # Forward these ports
  config.vm.network :forwarded_port, guest: 6379, host: 6379
  config.vm.network :forwarded_port, guest: 80, host: 8977
  config.vm.network :forwarded_port, guest: 27017, host: 27017
  config.vm.network :forwarded_port, guest: 28017, host: 28017  

  # Set virtual machine memory size
  config.vm.provider :virtualbox do |vbox|
    vbox.customize ["modifyvm", :id, "--memory", 1024]
  end

  # Start up
  config.vm.provision :shell, :path => "initMongoDB.sh"
  config.vm.provision :shell, :path => "initRedis.sh"
  config.vm.provision :shell, :path => "initDart.sh"
  config.vm.provision :shell, :path => "initAtcServer.sh"
  

end
