# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "Ask the Crowds Server" do
  end
  config.vm.box = "Ubuntu Server 12.04 amd64"
  #
  # THE URL FROM WHERE THE 'CONFIG.VM.BOX' BOX WILL BE FETCHED IF IT
  # DOESN'T ALREADY EXIST ON THE USER'S SYSTEM.
  config.vm.box_url = "http://goo.gl/8kWkm"

  # Forward these ports
  config.vm.network :forwarded_port, guest: 6379, host: 6379
  config.vm.network :forwarded_port, guest: 8977, host: 80

  # Set virtual machine memory size
  config.vm.provider :virtualbox do |vbox|
    vbox.customize ["modifyvm", :id, "--memory", 1024]
  end

  # Start up
  config.vm.provision :shell, :path => "initRedis.sh"
  config.vm.provision :shell, :path => "initDart.sh"

end
