# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "CentOS 6.4 x86_64"
  #
  # THE URL FROM WHERE THE 'CONFIG.VM.BOX' BOX WILL BE FETCHED IF IT
  # DOESN'T ALREADY EXIST ON THE USER'S SYSTEM.
  config.vm.box_url = "http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130427.box"

  # Forward these ports
  config.vm.network :forwarded_port, guest: 6379, host: 6379

  # Set virtual machine memory size
  config.vm.provider :virtualbox do |vbox|
    vbox.customize ["modifyvm", :id, "--memory", 1024]
  end

  # Start up
  config.vm.provision :shell, :path => "initRedis.sh"
  config.vm.provision :shell, :path => "initDart.sh"

  # Additions update
  # In order to auto-update vbox guest additions you must run:
  #   > vagrant plugin install vagrant-vbguest

  # Undocumented API - MAY BREAK
  # See: https://github.com/mitchellh/vagrant/issues/1736

  if Vagrant.plugin("2").manager.config.has_key? :vbguest
    config.vbguest.no_remote = true
    config.vbguest.iso_path = "#{ENV['VBOX_INSTALL_PATH']}/VBoxGuestAdditions.iso"
  end
end
